
package org.gepir;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import ch.ean.gepir.request.GepirVersion2Request;
import ch.ean.gepir.response.GepirVersion2Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "routerSoap", targetNamespace = "http://www.gepir.org/")
@XmlSeeAlso({
    ch.ean.gepir.response.ObjectFactory.class,
    ch.ean.gepir.request.ObjectFactory.class,
    org.gepir.ObjectFactory.class
})
public interface RouterSoap {


    /**
     * Gepir Server Swiss for client version 2
     * 
     * @param parameters
     * @return
     *     returns ch.ean.gepir.response.GepirVersion2Response
     */
    @WebMethod(operationName = "GepirVersion2", action = "http://gepir.ean.ch/GepirVersion2")
    @WebResult(name = "GepirVersion2Response", targetNamespace = "http://gepir.ean.ch/Response", partName = "parameters")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GepirVersion2Response gepirVersion2(
        @WebParam(name = "GepirVersion2Request", targetNamespace = "http://gepir.ean.ch/Request", partName = "parameters")
        GepirVersion2Request parameters);

    /**
     * Obtains the Party info of a GLN
     * 
     * @param partyGln
     * @return
     *     returns org.gepir.GepirParty
     */
    @WebMethod(operationName = "GetPartyByGLN", action = "http://www.gepir.org/GetPartyByGLN")
    @WebResult(name = "gepirParty", targetNamespace = "http://www.gepir.org/", partName = "GetPartyByGLNResult")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GepirParty getPartyByGLN(
        @WebParam(name = "GetPartyByGLN", targetNamespace = "http://www.gepir.org/", partName = "partyGln")
        GetPartyByGLN partyGln);

    /**
     * Obtains owner of a GLN
     * 
     * @param ownerGln
     * @return
     *     returns org.gepir.GepirParty
     */
    @WebMethod(operationName = "GetOwnerOfGLN", action = "http://www.gepir.org/GetOwnerOfGLN")
    @WebResult(name = "gepirParty", targetNamespace = "http://www.gepir.org/", partName = "GetOwnerOfGLNResult")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GepirParty getOwnerOfGLN(
        @WebParam(name = "GetOwnerOfGLN", targetNamespace = "http://www.gepir.org/", partName = "ownerGln")
        GetOwnerOfGLN ownerGln);

    /**
     * Obtains GLN based on a GTIN
     * 
     * @param partyGtin
     * @return
     *     returns org.gepir.GepirParty
     */
    @WebMethod(operationName = "GetPartyByGTIN", action = "http://www.gepir.org/GetPartyByGTIN")
    @WebResult(name = "gepirParty", targetNamespace = "http://www.gepir.org/", partName = "GetPartyByGTINResult")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GepirParty getPartyByGTIN(
        @WebParam(name = "GetPartyByGTIN", targetNamespace = "http://www.gepir.org/", partName = "partyGtin")
        GetPartyByGTIN partyGtin);

    /**
     * Obtains GLN based on a SSCC
     * 
     * @param partySscc
     * @return
     *     returns org.gepir.GepirParty
     */
    @WebMethod(operationName = "GetPartyBySSCC", action = "http://www.gepir.org/GetPartyBySSCC")
    @WebResult(name = "gepirParty", targetNamespace = "http://www.gepir.org/", partName = "GetPartyBySSCCResult")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GepirParty getPartyBySSCC(
        @WebParam(name = "GetPartyBySSCC", targetNamespace = "http://www.gepir.org/", partName = "partySscc")
        GetPartyBySSCC partySscc);

    /**
     * Obtains the Party info by name
     * 
     * @param requestData
     * @return
     *     returns org.gepir.GepirParty
     */
    @WebMethod(operationName = "GetPartyByName", action = "http://www.gepir.org/GetPartyByName")
    @WebResult(name = "gepirParty", targetNamespace = "http://www.gepir.org/", partName = "GetPartyByNameResult")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GepirParty getPartyByName(
        @WebParam(name = "GetPartyByName", targetNamespace = "http://www.gepir.org/", partName = "requestData")
        GetPartyByName requestData);

    /**
     * Obtains Item information based on a GTIN
     * 
     * @param requestItem
     * @return
     *     returns org.gepir.GepirItem
     */
    @WebMethod(operationName = "GetItemByGTIN", action = "http://www.gepir.org/GetItemByGTIN")
    @WebResult(name = "gepirItem", targetNamespace = "http://www.gepir.org/", partName = "GetItemByGTINResult")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GepirItem getItemByGTIN(
        @WebParam(name = "GetItemByGTIN", targetNamespace = "http://www.gepir.org/", partName = "requestItem")
        GetItemByGTIN requestItem);

    /**
     * Get Gepir Statistics
     * 
     * @param requestStat
     * @return
     *     returns org.gepir.GepirStatistics
     */
    @WebMethod(operationName = "GetStatistics", action = "http://www.gepir.org/GetStatistics")
    @WebResult(name = "gepirStatistics", targetNamespace = "http://www.gepir.org/", partName = "GetStatisticsResult")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GepirStatistics getStatistics(
        @WebParam(name = "GetStatistics", targetNamespace = "http://www.gepir.org/", partName = "requestStat")
        GetStatistics requestStat);

    /**
     * Get Gepir Authorization
     * 
     * @param requestAuthorization
     * @return
     *     returns org.gepir.GepirAuthorization
     */
    @WebMethod(operationName = "GetAuthorization", action = "http://www.gepir.org/GetAuthorization")
    @WebResult(name = "gepirAuthorization", targetNamespace = "http://www.gepir.org/", partName = "GetAuthorizationResult")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public GepirAuthorization getAuthorization(
        @WebParam(name = "GetAuthorization", targetNamespace = "http://www.gepir.org/", partName = "requestAuthorization")
        GetAuthorization requestAuthorization);

    /**
     * SetAuthorize
     * 
     */
    @WebMethod(operationName = "SessionAuthorize", action = "http://www.gepir.org/SessionAuthorize")
    @RequestWrapper(localName = "SessionAuthorize", targetNamespace = "http://www.gepir.org/", className = "org.gepir.SessionAuthorize")
    @ResponseWrapper(localName = "SessionAuthorizeResponse", targetNamespace = "http://www.gepir.org/", className = "org.gepir.SessionAuthorizeResponse")
    public void sessionAuthorize();

    /**
     * Hello World
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://www.gepir.org/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://www.gepir.org/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://www.gepir.org/", className = "org.gepir.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://www.gepir.org/", className = "org.gepir.HelloWorldResponse")
    public String helloWorld();

}
