
package org.gs1.ws.gepir;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;

import org.gs1.ws.gepir4.GetItemByGTIN;
import org.gs1.ws.gepir4.GetItemByGTINResponse;
import org.gs1.ws.gepir4.GetKeyLicensee;
import org.gs1.ws.gepir4.GetKeyLicenseeResponse;
import org.gs1.ws.gepir4.GetPartyByName;
import org.gs1.ws.gepir4.GetPartyByNameResponse;
import org.gs1.ws.gepir4.GetPrefixLicensee;
import org.gs1.ws.gepir4.GetPrefixLicenseeResponse;
import org.gs1.ws.gepir4.GetRootDirectory;
import org.gs1.ws.gepir4.GetRootDirectoryResponse;
import org.gs1.ws.gepir4.GetRouterDetail;
import org.gs1.ws.gepir4.GetRouterDetailResponse;

import gs1.gepir.request_header.xsd._4.RequestHeaderType;
import gs1.gepir.response_header.xsd._4.ResponseHeaderType;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "Gepir4xService", targetNamespace = "http://gepir4.ws.gs1.org/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso(
{
	gs1.gepir.gepir_common.xsd._4.ObjectFactory.class, gs1.gepir.gepir_item.xsd._4.ObjectFactory.class,
	gs1.gepir.gepir_item_ext.xsd._4.ObjectFactory.class, gs1.gepir.gepir_party.xsd._4.ObjectFactory.class,
	gs1.gepir.gepir_party_ext.xsd._4.ObjectFactory.class, gs1.gepir.get_item_by_gtin.xsd._4.ObjectFactory.class,
	gs1.gepir.get_key_licensee.xsd._4.ObjectFactory.class, gs1.gepir.get_party_by_name.xsd._4.ObjectFactory.class,
	gs1.gepir.get_prefix_licensee.xsd._4.ObjectFactory.class, gs1.gepir.get_root_directory.xsd._4.ObjectFactory.class,
	gs1.gepir.get_router_detail.xsd._4.ObjectFactory.class, gs1.gepir.request_header.xsd._4.ObjectFactory.class,
	gs1.gepir.response_header.xsd._4.ObjectFactory.class, gs1.gepir.root_directory.xsd._4.ObjectFactory.class,
	gs1.gepir.router_detail.xsd._4.ObjectFactory.class, gs1.shared.shared_common.xsd._3.ObjectFactory.class,
	org.gs1.ws.gepir4.ObjectFactory.class
})
public interface Gepir4XService
{

	/**
	 *
	 * @param result
	 * @param responseHeader
	 * @param requestHeader
	 * @param parameters
	 */
	@WebMethod
	public void getPrefixLicensee(
		@WebParam(name = "getPrefixLicensee", targetNamespace = "http://gepir4.ws.gs1.org/", partName = "parameters") GetPrefixLicensee parameters,
		@WebParam(name = "requestHeader", targetNamespace = "http://gepir4.ws.gs1.org/", header = true, partName = "requestHeader") RequestHeaderType requestHeader,
		@WebParam(name = "getPrefixLicenseeResponse", targetNamespace = "http://gepir4.ws.gs1.org/", mode = WebParam.Mode.OUT, partName = "result") Holder<GetPrefixLicenseeResponse> result,
		@WebParam(name = "responseHeader", targetNamespace = "http://gepir4.ws.gs1.org/", header = true, mode = WebParam.Mode.OUT, partName = "responseHeader") Holder<ResponseHeaderType> responseHeader);

	/**
	 *
	 * @param result
	 * @param responseHeader
	 * @param parameters
	 */
	@WebMethod
	public void getRootDirectory(
		@WebParam(name = "getRootDirectory", targetNamespace = "http://gepir4.ws.gs1.org/", partName = "parameters") GetRootDirectory parameters,
		@WebParam(name = "getRootDirectoryResponse", targetNamespace = "http://gepir4.ws.gs1.org/", mode = WebParam.Mode.OUT, partName = "result") Holder<GetRootDirectoryResponse> result,
		@WebParam(name = "responseHeader", targetNamespace = "http://gepir4.ws.gs1.org/", header = true, mode = WebParam.Mode.OUT, partName = "responseHeader") Holder<ResponseHeaderType> responseHeader);

	/**
	 *
	 * @param result
	 * @param responseHeader
	 * @param parameters
	 */
	@WebMethod
	public void getRouterDetail(
		@WebParam(name = "getRouterDetail", targetNamespace = "http://gepir4.ws.gs1.org/", partName = "parameters") GetRouterDetail parameters,
		@WebParam(name = "getRouterDetailResponse", targetNamespace = "http://gepir4.ws.gs1.org/", mode = WebParam.Mode.OUT, partName = "result") Holder<GetRouterDetailResponse> result,
		@WebParam(name = "responseHeader", targetNamespace = "http://gepir4.ws.gs1.org/", header = true, mode = WebParam.Mode.OUT, partName = "responseHeader") Holder<ResponseHeaderType> responseHeader);

	/**
	 *
	 * @param result
	 * @param responseHeader
	 * @param requestHeader
	 * @param parameters
	 */
	@WebMethod
	public void getKeyLicensee(
		@WebParam(name = "getKeyLicensee", targetNamespace = "http://gepir4.ws.gs1.org/", partName = "parameters") GetKeyLicensee parameters,
		@WebParam(name = "requestHeader", targetNamespace = "http://gepir4.ws.gs1.org/", header = true, partName = "requestHeader") RequestHeaderType requestHeader,
		@WebParam(name = "getKeyLicenseeResponse", targetNamespace = "http://gepir4.ws.gs1.org/", mode = WebParam.Mode.OUT, partName = "result") Holder<GetKeyLicenseeResponse> result,
		@WebParam(name = "responseHeader", targetNamespace = "http://gepir4.ws.gs1.org/", header = true, mode = WebParam.Mode.OUT, partName = "responseHeader") Holder<ResponseHeaderType> responseHeader);

	/**
	 *
	 * @param result
	 * @param responseHeader
	 * @param requestHeader
	 * @param parameters
	 */
	@WebMethod
	public void getPartyByName(
		@WebParam(name = "getPartyByName", targetNamespace = "http://gepir4.ws.gs1.org/", partName = "parameters") GetPartyByName parameters,
		@WebParam(name = "requestHeader", targetNamespace = "http://gepir4.ws.gs1.org/", header = true, partName = "requestHeader") RequestHeaderType requestHeader,
		@WebParam(name = "getPartyByNameResponse", targetNamespace = "http://gepir4.ws.gs1.org/", mode = WebParam.Mode.OUT, partName = "result") Holder<GetPartyByNameResponse> result,
		@WebParam(name = "responseHeader", targetNamespace = "http://gepir4.ws.gs1.org/", header = true, mode = WebParam.Mode.OUT, partName = "responseHeader") Holder<ResponseHeaderType> responseHeader);

	/**
	 *
	 * @param result
	 * @param responseHeader
	 * @param requestHeader
	 * @param parameters
	 */
	@WebMethod
	public void getItemByGTIN(
		@WebParam(name = "getItemByGTIN", targetNamespace = "http://gepir4.ws.gs1.org/", partName = "parameters") GetItemByGTIN parameters,
		@WebParam(name = "requestHeader", targetNamespace = "http://gepir4.ws.gs1.org/", header = true, partName = "requestHeader") RequestHeaderType requestHeader,
		@WebParam(name = "getItemByGTINResponse", targetNamespace = "http://gepir4.ws.gs1.org/", mode = WebParam.Mode.OUT, partName = "result") Holder<GetItemByGTINResponse> result,
		@WebParam(name = "responseHeader", targetNamespace = "http://gepir4.ws.gs1.org/", header = true, mode = WebParam.Mode.OUT, partName = "responseHeader") Holder<ResponseHeaderType> responseHeader);

}
